function [fitresult, gof] = createFit(t, H)
%CREATEFIT(T,H)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: H
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Dec-2018 00:03:31


%% Fit: 'untitled fit 1'.
z=[0 0.008 0.012 0.014 0.016 0.028 0.045 0.050 0.052 0.064 0.080 0.101 0.124 0.300 0.380 0.430 0.430 0.440 0.480 0.500 0.570 0.620 0.970];
d_MPars=[0 36.14 55.72 66.99 63.10 145.88 236.59 215.77 289.73 335.74 390.84 463.45 660.69 1577.61 2766.94 2546.83 2937.65 2831.39 3147.75 3467.37 3681.29 3999.45 7244.36];
d_meter=(3.08567758*(10^16)*(10^6))*d_MPars;
vel=(((z+1).^2-1)./((z+1).^2+1)).*299792458;
H=vel./d_meter;
t=-d_meter/299792458;
[xData, yData] = prepareCurveData( t, H );

% Set up fittype and options.
ft = fittype( 'poly3' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'H vs. t', 'fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel t
ylabel H
grid on


